b1 = Bike.find_or_create_by(color: "red", date_introduced: Time.now, miles: 10)
b2 = Bike.find_or_create_by(color: "blue", date_introduced: Time.now, miles: 20)
b3 = Bike.find_or_create_by(color: "green", date_introduced: Time.now, miles: 30)
b4 = Bike.find_or_create_by(color: "yellow", date_introduced: Time.now, miles: 40)
b5 = Bike.find_or_create_by(color: "red", date_introduced: Time.now, miles: 50)
b6 = Bike.find_or_create_by(color: "blue", date_introduced: Time.now, miles: 60)
b7 = Bike.find_or_create_by(color: "green", date_introduced: Time.now, miles: 70)
b8 = Bike.find_or_create_by(color: "yellow", date_introduced: Time.now, miles: 80)
b9 = Bike.find_or_create_by(color: "red", date_introduced: Time.now, miles: 90)
b10 = Bike.find_or_create_by(color: "blue", date_introduced: Time.now, miles: 100)
b11 = Bike.find_or_create_by(color: "green", date_introduced: Time.now, miles: 110)
b12 = Bike.find_or_create_by(color: "yellow", date_introduced: Time.now, miles: 120)
b13 = Bike.find_or_create_by(color: "red", date_introduced: Time.now, miles: 130)

rider1 = Rider.find_or_create_by(name: "Joe", has_membership: true)

